### ISSUE TITLE
UMLS to CSV script: improve the mapping of codes to dbxrefs

### ISSUE THREAD

**Issue by AlanSimmons** [dbmi-pitt/ubkg#25]
# Issue
@benstear has been working with the section of code in the [UMLS-CSV converter script](https://github.com/dbmi-pitt/ubkg/blob/main/scripts/Jonathan/OWLNETS-UMLS-GRAPH-12.py) to integrate a large ontology. He has identified a number of improvements to the code that maps node codes to cross-referenced CUIs. As I understand, the code works much faster with large data sets.

The following image compares the existing code section to the revised code.

![image](https://user-images.githubusercontent.com/10928372/210442561-63f40b24-83d3-4a50-8ca4-b211b1c75f36.png)

The new code would need to be regression-tested against the MP ontology, which presents an edge case of multiple codes sharing the same cross-reference.

**Comment by benstear** [comment]
Description of changes:

- changed iterrows() to itertuples()
- changed node_idCUIs and nmCUI to be sets instead of lists. This is the most significant change, sets can be searched much much faster than lists apparently.
- Instead of adding an empty string to  node_idCUIs and nmCUI , I add a UUID instead. This is because if you add multiple empty strings the set will obviously just ignore them. They can be changed to empty strings afterward By filtering for type(UUID) or something like that.
- I also add the index along with the CUI because Im not sure order will be preserved within the sets. I just cast the set to a dict and sort on the key (aka the index) afterwards.

**Comment by AlanSimmons** [comment]
Because I will need to regression test this against the entire set of "base ontologies", I will make the recommended enhancements in the source and submit the PR. I realize that this is not the standard fork/branch method in github; however, if I pulled in a PR from Ben and then found an error during testing, I'd still have to go into the code. I might as well change the code myself from the beginning.

Once we identify all of the use cases (the different flavors of ontologies that we might integrate), adding a new ontology would be a little more straightforward. In other words, I don't intend to keep gates around this code forever.

**Comment by benstear** [comment]
Sounds good to me, thanks.

**Comment by AlanSimmons** [comment]
@benstear 

> Instead of adding an empty string to node_idCUIs and nmCUI , I add a UUID instead. This is because if you add multiple empty strings the set will obviously just ignore them. They can be changed to empty strings afterward By filtering for type(UUID) or something like that.
I also add the index along with the CUI because Im not sure order will be preserved within the sets. I just cast the set to a dict and sort on the key (aka the index) afterwards.

Can you provide code snippets for the filtering by type UUID and casting/sorting?

My concern here is that the list nmCUI is ordered and aligned with node_metadata , while the set is not ordered. The CUI column in node_metadata is supposed to match a node (node_id column) with a cross-referenced CUI. If the elements in nmCUI are not sorted correctly, the cross-references will be incorrect, breaking a significant feature of the sections of the resulting knowledge graph.

**Comment by benstear** [comment]
Because the sets are not ordered, I append the INDEX variable along with the x variable so that after the for loop finishes you can cast the sets to lists of tuples and then to a data frame (or something like this) and then merge on the INDEX column and preserve order. Would that work?

**Comment by AlanSimmons** [comment]
@benstear is working on the code changes in the Data Distillery fork of this repo.

**Comment by benstear** [comment]
@AlanSimmons I started testing both versions of this code (one using sets and the other using lists) with the MP ontology to see if the results were identical. They were not identical although after fixing the issue they both produce the exact same list of CUIs.

I will give an overview of the changes because they have changed slightly.

1. Change .iterrows() to .itertuples() in the outermost for loop. This can speed things up but it's still a minor change compared to changing the lists to sets. (see [here](https://stackoverflow.com/questions/24870953/does-pandas-iterrows-have-performance-issues) for iterrows vs itertuples).
2. Change node_idCUIs and nmCUI to be sets instead of lists. This way the first if statement can search for `x` in a set and not a list. This change makes a dramatic difference in speed. This is because searching a list is O(n) and searching a set is O(1), see [here]('https://wiki.python.org/moin/TimeComplexity'). Because the sets only contain unique values and they are unordered, I add a tuple containing the current iteration (defined as `INDEX` in the code) as well as the CUI. This ensures that each element is unique (in the case when we have to add the same CUI multiple times) and allows us to order the elements of the set based on the INDEX of each tuple after the for loop is finished. Iim using the INDEX in place of the uuid now because it's simpler and can be sorted based on insertion order, while the uuids can't be.
3. Adding tuples instead of CUIs to the sets was giving me an issue though because when the `(x in node_idCUIs)` code gets executed, it's searching for a CUI string in a set of tuples which will obviously always return `False`. To fix this I just added another set which I call `eset` for 'existence set'. I add the CUI string to this set and then search in this set so now the search code looks like `(x in eset)`.
4. After the for loop is done I turn the set of tuples into a dict object in the form INDEX: CUI. Then I sort the dict based on key (INDEX) and then I take the values (CUIs) which are now ordered.
```
d = dict(node_idCUIs) # convert set of tuples to dict.
ordered_cui_dict = {key:d[key] for key in sorted(d.keys())} # sort dict based on key (INDEX)
v = list(ordered_cui_dict.values()) # get values (CUIs)
```
![set_v_list_bigO](https://user-images.githubusercontent.com/37672093/224706590-c1f73e1d-c213-43e8-a693-f32f92e0f186.png)

**Comment by AlanSimmons** [comment]
@benstear Thank you for working on this.

As we discussed in the March 16 Data Distillery meeting, we'll need to modify this logic so that it is possible to map multiple codes to the same concept via dbxref. That's a fundamental change to the current logic, which assumes that each code from an ingested ontology can only be associated with one concept via dbxref. 

Perhaps the logic change means that we don't have to worry with any of this. I'm not sure. If we do have to loop through a collection of concepts, however, we'll know that sets are a faster solution than lists.

**Comment by AlanSimmons** [comment]
Because of the amount of commentary, only a reference to this issue is transferred to the new ubkg-etl repo.

**Comment by AlanSimmons** [comment]
@benstear @computationdoc

I went back over the code in OWLNETS-UMLS-GRAPH.py. I don't think that we have to worry about replacing lists with sets. I don't think that we need the sorting loop at all: in fact, we can replace the whole thing with a single line of code. This change also addresses the need to allow multiple nodes to map to the same CUI.

Before starting the loop, the code orders CUIs to which a node can associate in order of preference:

```node_metadata['cuis'] = node_metadata[['nodeCUIs', 'CUI_CODEs', 'XrefCUIs', 'base64cui']].values.tolist()```

This order, from left to right, corresponds to:
1. nodeCUIs - the UMLS CUI for a cross-reference that existed previously in the UMLS CSVs
2. CUI_CODES - the UMLS CUI for the node that existed previously in the UMLS CSVs.
3. XrefCUIs - the non-UMLS CUI for the cross-reference that existed previously in the ontology CSVs--i.e., after a prior ingestion.
4. base64cui - the base64 CUI (base 64 encoding of the node ID) for a node that does not currently exist in the ontology CSVs.

CUI_CODES is usually a one-element list, and XrefCUIs is often a multi-element list.

(One challenge here has been that the names of the items are confusing--nodeCUIs is actually for UMLS CUIs of cross-references, and XrefCUIs are non-UMLS CUIs for cross-references.)

The code then further refines the contents of the cui list:

```
# remove nan, flatten, and remove duplicates - retains order of elements which is key to consistency
node_metadata['cuis'] = node_metadata['cuis'].apply(lambda x: [i for i in x if i == i])
node_metadata['cuis'] = node_metadata['cuis'].apply(lambda x: [i for row in x for i in row])
node_metadata['cuis'] = node_metadata['cuis'].apply(lambda x: pd.unique(x)).apply(list)

```

The selection logic is currently:

```# iterate to select one CUI from cuis in row order - we ensure each node_id has its own distinct CUI
# each node_id is assigned one CUI distinct from all others' CUIs to ensure no self-reference in edgelist

node_idCUIs = []
nmCUI = []
for index, rows in node_metadata.iterrows():
    addedone = False
    for x in rows.cuis:
        if ((x in node_idCUIs) | (addedone == True)):
            dummy = 0
        else:
            nmCUI.append(x)
            node_idCUIs.append(x)
            addedone = True
    # JAS 17 oct 2022
    # For the edge case in which multiple nodes have the same cross-reference AND the
    # cross-reference maps to a single CUI (the case for around 20 nodes in MP--e.g., all
    # those that share CL 0000959 as a cross-reference), only one of the nodes will be
    # assigned the CUI of the cross-reference. The rest of the nodes will lose the
    # cross-reference.
    # The following block keeps the nmCUI list the same size as node_metadata['CUI'].
    if addedone == False:
        nmCUI.append('')
        node_idCUIs.append('')

node_metadata['CUI'] = nmCUI
```
However, that logic is essentially the same as:

```
# Assign the CUI in order of precedence. This should be the first element in the list of cuis.
node_metadata['CUI']=node_metadata['cuis'].str[0]
```

This also handles the case in which more than one node cross-refers to the same single CUI. Each node will have a list that includes the CUI for the cross-reference and their own base64 CUIs: because the CUI for the cross-reference comes first in the list, it will be selected.

**Comment by AlanSimmons** [comment]
I regenerated a set of CSVs and imported them into a local neo4j and compared it with the current production version. The node-CUI mappings in the local instance were from the new, simpler logic; the production mappings were from the older logic.

I checked mappings for two known cases:
1. MP, which had a number of nodes that mapped to CL:0000959. 
2. Azimuth, which has a number of nodes that map to CL, too.

My results were identical--e.g., these codes from MP map to CL:0000959:


CodeID
--
1 | "MP 0009926"
2 | "MP 0009927"
3 | "MP 0009925"
4 | "MP 0009920"

And these AZ codes map to CL:0000084:

CodeID
--
1 | "AZ 0000126"
2 | "AZ 0000069"
3 | "AZ 0000019

At one point, the MP ontology had 20 codes that mapped to CL:0000959, per in-line documentation in the script. Now there are only 3 in the nodes file. 

The fact that the two instances show the same thing makes sense, given that the generation logic is very similar. 

It looks like we can replace the older logic.

**Comment by AlanSimmons** [comment]
@benstear  Can you test in your version of the script?

All that you need to do is comment out the block that loops through node_metadata and assigns to nmCUI and replace it with the statement
```
node_metadata['CUI']=node_metadata['cuis'].str[0]
```

I suspect that this will result in a faster-running script.

**Comment by AlanSimmons** [comment]
PR made in ubkg-etl repo. I will close this issue after merging my branch.

**Comment by AlanSimmons** [comment]
Merged PR in ubkg-etl.
